#!/bin/bash

mkdir -p $HOME/Documents/nemo;
cd $HOME/Documents/nemo;

section=$1

if [ "$section" = ls ]
then
	ls
else
	page=$2

mkdir -p $HOME/Documents/nemo/$section;
cd $HOME/Documents/nemo/$section;
newdir=$HOME/Documents/nemo/$section


if [ "$page" = ls ]
then
	ls
else

	if [ -f $newdir/$page ]
	then
		xdg-open $page
	else
		touch $page
		xdg-open $page
	fi
fi
fi
